"""fixing status 500 problem

Revision ID: 7c60eb9de756
Revises: ff6c33762d6e
Create Date: 2025-02-13 19:46:02.627026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c60eb9de756'
down_revision: Union[str, None] = 'ff6c33762d6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user.py', 'email',
               existing_type=sa.VARCHAR(length=320),
               type_=sa.String(length=250),
               existing_nullable=False)
    op.drop_index('ix_user_email', table_name='user.py')
    op.create_unique_constraint(None, 'user.py', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user.py', type_='unique')
    op.create_index('ix_user_email', 'user.py', ['email'], unique=True)
    op.alter_column('user.py', 'email',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=320),
               existing_nullable=False)
    # ### end Alembic commands ###
