"""Fix foreign key

Revision ID: af9bff9b8bf8
Revises: 7c60eb9de756
Create Date: 2025-02-14 12:26:39.346709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af9bff9b8bf8'
down_revision: Union[str, None] = '7c60eb9de756'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
