"""Add confirmed column to user.py table

Revision ID: ff6c33762d6e
Revises: 021b64fac706
Create Date: 2025-02-13 18:50:41.901366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff6c33762d6e'
down_revision: Union[str, None] = '021b64fac706'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user.py', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user.py', 'confirmed')
    # ### end Alembic commands ###
